apiVersion: v1
kind: Service
metadata:
  name: cart-service
spec:
  type: NodePort
  selector:
    app: cart
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-deployment
  labels:
    app: cart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
      - name: nginx
        image: {{IMAGE}}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      dnsPolicy: ClusterFirst
      restartPolicy: Always